import { Providers } from "@/components/Providers";
import { TheFooter } from "@/components/TheFooter";
import { TheHeader } from "@/components/TheHeader";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
require("dotenv").config();

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <TheHeader />
          <main>{children}</main>
          <TheFooter />
        </Providers>
      </body>
    </html>
  );
}
